language: python
python:
  - "3.8"
install: pip install tox
jobs:
  include:
    - script: tox -e pytest-unit
    - script: tox -e pytest-integration
    - script: tox -e mypy
    - script: tox -e flake8
